// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jsptozrmlibvxzfkvrec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpzcHRvenJtbGlidnh6Zmt2cmVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMzUxNzgsImV4cCI6MjA2MzYxMTE3OH0.6kDoWzfumM_LtxFc-qIpC2UDswGca4fVxtrtUTXmOag";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});